name: 'pharmawatch'
version: '1.0.0'
config-version: 2

profile: 'pharmawatch'

model-paths: ["models"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
analysis-paths: ["analyses"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  pharmawatch:
    staging:
      +materialized: view
    marts:
      +materialized: table
